// ecommerce-dashboard/src/lib/components/ui/Card.tsx
import React from 'react'
import { cn } from '@/utils/cn'

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  title?: string
  subtitle?: string
  variant?: 'default' | 'outlined' | 'elevated' | 'glass'
  padding?: 'none' | 'sm' | 'md' | 'lg'
  hover?: boolean
  header?: React.ReactNode
  footer?: React.ReactNode
}

const Card = React.forwardRef<HTMLDivElement, CardProps>(
  ({
    className,
    title,
    subtitle,
    variant = 'default',
    padding = 'md',
    hover = false,
    header,
    footer,
    children,
    ...props
  }, ref) => {
    const baseClasses = 'bg-white rounded-2xl transition-all duration-200'
    
    const variantClasses = {
      default: 'border border-gray-200',
      outlined: 'border-2 border-gray-200',
      elevated: 'shadow-lg border border-gray-100',
      glass: 'backdrop-blur-sm bg-white/80 border border-white/20 shadow-xl'
    }
    
    const hoverClasses = hover ? 'hover:shadow-md hover:border-gray-300 cursor-pointer' : ''
    
    const paddingClasses = {
      none: 'p-0',
      sm: 'p-4',
      md: 'p-6',
      lg: 'p-8'
    }

    const hasHeader = header || title || subtitle
    const hasFooter = footer

    return (
      <div
        ref={ref}
        className={cn(
          baseClasses,
          variantClasses[variant],
          hoverClasses,
          className
        )}
        {...props}
      >
        {hasHeader && (
          <div className={cn(
            'border-b border-gray-200',
            paddingClasses[padding]
          )}>
            {header || (
              <div>
                {title && (
                  <h3 className="text-lg font-semibold text-gray-900">
                    {title}
                  </h3>
                )}
                {subtitle && (
                  <p className="text-sm text-gray-600 mt-1">
                    {subtitle}
                  </p>
                )}
              </div>
            )}
          </div>
        )}
        
        <div className={cn(paddingClasses[padding])}>
          {children}
        </div>
        
        {hasFooter && (
          <div className={cn(
            'border-t border-gray-200',
            paddingClasses[padding]
          )}>
            {footer}
          </div>
        )}
      </div>
    )
  }
)

Card.displayName = 'Card'

export default Card

// admin-panel/src/lib/components/ui/Card.vue
<template>
  <div :class="cardClasses">
    <!-- Header -->
    <div v-if="$slots.header || title" :class="headerClasses">
      <slot name="header">
        <h3 v-if="title" class="text-lg font-semibold text-gray-900">
          {{ title }}
        </h3>
        <p v-if="subtitle" class="text-sm text-gray-600">
          {{ subtitle }}
        </p>
      </slot>
    </div>
    
    <!-- Body -->
    <div :class="bodyClasses">
      <slot />
    </div>
    
    <!-- Footer -->
    <div v-if="$slots.footer" :class="footerClasses">
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  title?: string
  subtitle?: string
  variant?: 'default' | 'outlined' | 'elevated'
  padding?: 'none' | 'sm' | 'md' | 'lg'
  hover?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  padding: 'md',
  hover: false
})

const cardClasses = computed(() => {
  const baseClasses = 'bg-white rounded-2xl transition-all duration-200'
  
  const variantClasses = {
    default: 'border border-gray-200',
    outlined: 'border-2 border-gray-200',
    elevated: 'shadow-lg border border-gray-100'
  }
  
  const hoverClasses = props.hover ? 'hover:shadow-md hover:border-gray-300' : ''
  
  return [baseClasses, variantClasses[props.variant], hoverClasses].filter(Boolean).join(' ')
})

const headerClasses = computed(() => {
  const baseClasses = 'border-b border-gray-200'
  
  const paddingClasses = {
    none: 'p-0',
    sm: 'p-4',
    md: 'p-6',
    lg: 'p-8'
  }
  
  return [baseClasses, paddingClasses[props.padding]].join(' ')
})

const bodyClasses = computed(() => {
  const paddingClasses = {
    none: 'p-0',
    sm: 'p-4',
    md: 'p-6',
    lg: 'p-8'
  }
  
  return paddingClasses[props.padding]
})

const footerClasses = computed(() => {
  const baseClasses = 'border-t border-gray-200'
  
  const paddingClasses = {
    none: 'p-0',
    sm: 'p-4',
    md: 'p-6',
    lg: 'p-8'
  }
  
  return [baseClasses, paddingClasses[props.padding]].join(' ')
})
</script>
