// ecommerce-dashboard/src/lib/components/layout/Sidebar.tsx
import React from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { cn } from '@/utils/cn'

export interface SidebarItem {
  label: string
  href: string
  icon: React.ReactNode
  badge?: string | number
  children?: SidebarItem[]
}

export interface SidebarProps {
  items: SidebarItem[]
  isOpen?: boolean
  onToggle?: () => void
  className?: string
  logo?: React.ReactNode
  footer?: React.ReactNode
}

const Sidebar: React.FC<SidebarProps> = ({
  items,
  isOpen = true,
  onToggle,
  className,
  logo,
  footer
}) => {
  const pathname = usePathname()

  const isActiveLink = (href: string) => {
    return pathname === href || pathname.startsWith(href + '/')
  }

  const renderSidebarItem = (item: SidebarItem, level = 0) => {
    const isActive = isActiveLink(item.href)
    const hasChildren = item.children && item.children.length > 0
    
    const itemClasses = cn(
      'flex items-center justify-between px-4 py-3 text-sm font-medium rounded-xl transition-all duration-200',
      level > 0 && 'ml-4',
      isActive
        ? 'bg-gradient-to-r from-purple-600 to-blue-600 text-white shadow-lg'
        : 'text-gray-700 hover:bg-gray-100 hover:text-gray-900'
    )

    return (
      <div key={item.href}>
        <Link href={item.href} className={itemClasses}>
          <div className="flex items-center space-x-3">
            <span className={cn('flex-shrink-0', isActive ? 'text-white' : 'text-gray-400')}>
              {item.icon}
            </span>
            {isOpen && (
              <span className="truncate">{item.label}</span>
            )}
          </div>
          
          {isOpen && (
            <div className="flex items-center space-x-2">
              {item.badge && (
                <span className={cn(
                  'px-2 py-0.5 text-xs font-medium rounded-full',
                  isActive
                    ? 'bg-white/20 text-white'
                    : 'bg-purple-100 text-purple-800'
                )}>
                  {item.badge}
                </span>
              )}
              
              {hasChildren && (
                <svg
                  className={cn('w-4 h-4 transition-transform', isActive ? 'text-white' : 'text-gray-400')}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              )}
            </div>
          )}
        </Link>
        
        {hasChildren && isOpen && (
          <div className="mt-1 space-y-1">
            {item.children!.map(child => renderSidebarItem(child, level + 1))}
          </div>
        )}
      </div>
    )
  }

  return (
    <div className={cn(
      'flex flex-col bg-white border-r border-gray-200 transition-all duration-300',
      isOpen ? 'w-64' : 'w-16',
      className
    )}>
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-gray-200">
        {isOpen && logo && (
          <div className="flex items-center space-x-2">
            {logo}
          </div>
        )}
        
        {onToggle && (
          <button
            onClick={onToggle}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
        )}
      </div>
      
      {/* Navigation */}
      <nav className="flex-1 p-4 space-y-2 overflow-y-auto">
        {items.map(item => renderSidebarItem(item))}
      </nav>
      
      {/* Footer */}
      {footer && isOpen && (
        <div className="p-4 border-t border-gray-200">
          {footer}
        </div>
      )}
    </div>
  )
}

export default Sidebar

// admin-panel/src/components/layout/Sidebar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { 
  LayoutDashboard, 
  Users, 
  Shield, 
  Key, 
  BarChart3, 
  Settings, 
  LogOut,
  X
} from 'lucide-vue-next'

interface Emits {
  (e: 'close'): void
}

const emit = defineEmits<Emits>()
const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const navigationItems = [
  {
    name: 'Dashboard',
    href: '/',
    icon: LayoutDashboard,
    current: computed(() => route.path === '/')
  },
  {
    name: 'Users',
    href: '/users',
    icon: Users,
    current: computed(() => route.path === '/users')
  },

  {
    name: 'Analytics',
    href: '/analytics',
    icon: BarChart3,
    current: computed(() => route.path === '/analytics')
  },
  {
    name: 'Settings',
    href: '/settings',
    icon: Settings,
    current: computed(() => route.path === '/settings')
  }
]

const handleNavigation = (href: string) => {
  router.push(href)
  emit('close') // Close mobile sidebar after navigation
}

const handleLogout = () => {
  authStore.logout()
  router.push('/login')
}
</script>

<template>
  <div class="flex h-full flex-col bg-white shadow-xl">
    <!-- Header -->
    <div class="flex items-center justify-between px-6 py-4 border-b border-gray-200">
      <div class="flex items-center space-x-3">
        <div class="w-8 h-8 bg-gradient-to-br from-purple-600 to-blue-600 rounded-lg flex items-center justify-center">
          <Shield class="w-5 h-5 text-white" />
        </div>
        <h1 class="text-xl font-bold text-gray-900">Admin Panel</h1>
      </div>
      
      <!-- Mobile close button -->
      <button
        @click="emit('close')"
        class="lg:hidden p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
      >
        <X class="w-5 h-5" />
      </button>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 px-4 py-6 space-y-2 overflow-y-auto">
      <div
        v-for="item in navigationItems"
        :key="item.name"
        @click="handleNavigation(item.href)"
        class="group flex items-center px-3 py-2.5 text-sm font-medium rounded-xl cursor-pointer transition-all duration-200"
        :class="item.current.value
          ? 'bg-purple-50 text-purple-700 border-r-2 border-purple-600'
          : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'"
      >
        <component
          :is="item.icon"
          class="mr-3 h-5 w-5 flex-shrink-0 transition-colors"
          :class="item.current.value
            ? 'text-purple-600'
            : 'text-gray-400 group-hover:text-gray-500'"
        />
        {{ item.name }}
      </div>
    </nav>

    <!-- User Profile & Logout -->
    <div class="border-t border-gray-200 p-4">
      <!-- User Info -->
      <div class="flex items-center space-x-3 px-3 py-2 mb-3">
        <div class="w-10 h-10 bg-gradient-to-br from-purple-600 to-blue-600 rounded-lg flex items-center justify-center">
          <span class="text-sm font-semibold text-white">
            {{ authStore.user?.firstName?.[0] || 'A' }}{{ authStore.user?.lastName?.[0] || 'U' }}
          </span>
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-sm font-medium text-gray-900 truncate">
            {{ authStore.user?.firstName }} {{ authStore.user?.lastName }} || 'Admin User'
          </p>
          <p class="text-xs text-gray-500 truncate">
            {{ authStore.user?.role?.charAt(0).toUpperCase() + authStore.user?.role?.slice(1) || 'Admin' }}
          </p>
        </div>
      </div>

      <!-- Logout Button -->
      <button
        @click="handleLogout"
        class="w-full flex items-center px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-red-50 hover:text-red-700 rounded-xl transition-all duration-200 group"
      >
        <LogOut class="mr-3 h-5 w-5 text-gray-400 group-hover:text-red-500 transition-colors" />
        Sign out
      </button>
    </div>
  </div>
</template>

<style scoped>
/* Custom scrollbar for navigation */
nav::-webkit-scrollbar {
  width: 4px;
}

nav::-webkit-scrollbar-track {
  background: transparent;
}

nav::-webkit-scrollbar-thumb {
  background: #e5e7eb;
  border-radius: 2px;
}

nav::-webkit-scrollbar-thumb:hover {
  background: #d1d5db;
}
</style>
