// ecommerce-dashboard/src/components/forms/LoginForm.tsx
'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useAuth } from '@/hooks/useAuth';
import { Eye, EyeOff, ArrowRight } from 'lucide-react';

const loginSchema = z.object({
  email: z.string().email('Please enter a valid email address'),
  password: z.string().min(6, 'Password must be at least 6 characters'),
});

type LoginFormData = z.infer<typeof loginSchema>;

export function LoginForm() {
  const [showPassword, setShowPassword] = useState(false);
  const [isRegistering, setIsRegistering] = useState(false);
  const { login, register, loading, error } = useAuth();

  const {
    register: registerField,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<LoginFormData>({
    resolver: zodResolver(loginSchema),
  });

  const onSubmit = async (data: LoginFormData) => {
    try {
      if (isRegistering) {
        await register({
          email: data.email,
          password: data.password,
          role: 'USER',
        });
      } else {
        await login(data.email, data.password);
      }
    } catch (err) {
      console.error('Authentication error:', err);
    }
  };

  return (
    <div className="min-h-screen bg-white flex">
      {/* Left side - Login Form */}
      <div className="flex-1 flex items-center justify-center px-4 sm:px-6 lg:px-8">
        <div className="w-full max-w-sm space-y-8">
          {/* Header */}
          <div className="text-center">
            <h1 className="text-2xl font-semibold text-purple-600 mb-8">
              {isRegistering ? 'Create Account' : 'Sign in to Dashboard'}
            </h1>
          </div>

          {/* Form */}
          <form className="space-y-6" onSubmit={handleSubmit(onSubmit)}>
            <div className="space-y-4">
              {/* Email Field */}
              <div>
                <input
                  {...registerField('email')}
                  type="email"
                  autoComplete="email"
                  className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent placeholder-gray-400 text-gray-900 transition-all duration-200"
                  placeholder="Work email"
                />
                {errors.email && (
                  <p className="mt-2 text-sm text-red-500">{errors.email.message}</p>
                )}
              </div>

              {/* Password Field */}
              <div>
                <div className="relative">
                  <input
                    {...registerField('password')}
                    type={showPassword ? 'text' : 'password'}
                    autoComplete="current-password"
                    className="w-full px-4 py-3 pr-12 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent placeholder-gray-400 text-gray-900 transition-all duration-200"
                    placeholder="Password"
                  />
                  <button
                    type="button"
                    className="absolute inset-y-0 right-0 pr-4 flex items-center"
                    onClick={() => setShowPassword(!showPassword)}
                  >
                    {showPassword ? (
                      <EyeOff className="h-5 w-5 text-gray-400 hover:text-gray-600" />
                    ) : (
                      <Eye className="h-5 w-5 text-gray-400 hover:text-gray-600" />
                    )}
                  </button>
                </div>
                {errors.password && (
                  <p className="mt-2 text-sm text-red-500">{errors.password.message}</p>
                )}
              </div>
            </div>

            {/* Links */}
            <div className="flex justify-between text-sm">
              <button
                type="button"
                onClick={() => {
                  setIsRegistering(!isRegistering);
                  reset();
                }}
                className="text-purple-600 hover:text-purple-700 font-medium"
              >
                {isRegistering ? 'Sign in' : 'Create Account'}
              </button>
              <button
                type="button"
                className="text-purple-600 hover:text-purple-700 font-medium"
              >
                Forgot Password
              </button>
            </div>

            {/* Error Message */}
            {error && (
              <div className="rounded-xl bg-red-50 border border-red-200 p-4">
                <div className="text-sm text-red-700">{error}</div>
              </div>
            )}

            {/* Submit Button */}
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-gray-100 hover:bg-gray-200 text-gray-800 font-medium py-3 px-4 rounded-xl transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
            >
              {loading ? (
                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-gray-600"></div>
              ) : (
                <>
                  {isRegistering ? 'Create Account' : 'Sign in'}
                </>
              )}
            </button>

            {/* Social Login Buttons */}
            <div className="space-y-3">
              <button
                type="button"
                className="w-full bg-white border border-gray-200 hover:bg-gray-50 text-gray-700 font-medium py-3 px-4 rounded-xl transition-all duration-200 flex items-center justify-between"
              >
                <div className="flex items-center">
                  <div className="w-5 h-5 mr-3">
                    <svg viewBox="0 0 24 24" className="w-full h-full">
                      <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
                      <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                      <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                      <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
                    </svg>
                  </div>
                  Sign in with Google
                </div>
                <ArrowRight className="w-4 h-4" />
              </button>

              <button
                type="button"
                className="w-full bg-white border border-gray-200 hover:bg-gray-50 text-gray-700 font-medium py-3 px-4 rounded-xl transition-all duration-200 flex items-center justify-between"
              >
                <div className="flex items-center">
                  <div className="w-5 h-5 mr-3">
                    <svg viewBox="0 0 24 24" className="w-full h-full" fill="currentColor">
                      <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                    </svg>
                  </div>
                  Sign in with GitHub
                </div>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>

            {/* Demo Credentials */}
            <div className="text-center">
              <p className="text-xs text-gray-500">
                Demo: admin@example.com / password123
              </p>
            </div>
          </form>

          {/* Footer Links */}
          <div className="flex justify-center space-x-6 text-xs text-gray-500">
            <button className="hover:text-gray-700">Privacy Policy</button>
            <button className="hover:text-gray-700">Terms of Service</button>
            <button className="hover:text-gray-700">Privacy & Security</button>
          </div>
        </div>
      </div>

      {/* Right side - Background Pattern */}
      <div className="hidden lg:flex flex-1 bg-gradient-to-br from-purple-50 to-purple-100 relative overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute inset-0" style={{
            backgroundImage: `repeating-linear-gradient(
              45deg,
              transparent,
              transparent 10px,
              rgba(139, 69, 193, 0.1) 10px,
              rgba(139, 69, 193, 0.1) 20px
            )`
          }}></div>
        </div>
        <div className="flex items-center justify-center w-full">
          <div className="text-center text-purple-600 max-w-md">
            <h2 className="text-3xl font-bold mb-4">Welcome to Dashboard</h2>
            <p className="text-lg opacity-80">
              Manage your ecommerce business with powerful analytics and insights.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// admin-panel/src/components/auth/LoginForm.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useForm } from 'vee-validate'
import * as yup from 'yup'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { Eye, EyeOff, Shield, Loader2 } from 'lucide-vue-next'

const authStore = useAuthStore()
const router = useRouter()
const showPassword = ref(false)
const loginError = ref('')

const schema = yup.object({
  email: yup.string().email('Invalid email').required('Email is required'),
  password: yup.string().min(6, 'Password must be at least 6 characters').required('Password is required')
})

const { defineField, handleSubmit, errors } = useForm({
  validationSchema: schema,
  initialValues: {
    email: 'admin@example.com',
    password: 'password123'
  }
})

const [email, emailAttrs] = defineField('email')
const [password, passwordAttrs] = defineField('password')

const handleLogin = async () => {
  loginError.value = ''
  
  try {
    const values = { email: email.value, password: password.value }
    const result = await authStore.login(values)
    if (result.success) {
      // Navigate to dashboard on successful login
      await router.push('/')
    } else {
      loginError.value = result.error || 'Login failed'
    }
  } catch (error: any) {
    loginError.value = error.message || 'Login failed'
    console.error('Login failed:', error)
  }
}

const togglePasswordVisibility = () => {
  showPassword.value = !showPassword.value
}
</script>

<template>
  <div class="min-h-screen flex">
    <!-- Left Side - Login Form -->
    <div class="flex-1 flex items-center justify-center bg-white px-4 sm:px-6 lg:px-8">
      <div class="max-w-md w-full space-y-8">
        <!-- Header -->
        <div class="text-center">
          <div class="mx-auto h-16 w-16 flex items-center justify-center rounded-full bg-purple-600 shadow-lg">
            <Shield class="h-8 w-8 text-white" />
          </div>
          <h2 class="mt-6 text-3xl font-bold text-gray-900">
            Sign in to Admin Panel
          </h2>
          <p class="mt-2 text-sm text-gray-600">
            Access your dashboard and manage your system
          </p>
        </div>

        <!-- Login Form -->
        <div class="space-y-6">
          <div class="space-y-6">
            <!-- Email -->
            <div>
              <input
                id="email"
                v-model="email"
                v-bind="emailAttrs"
                type="email"
                autocomplete="email"
                :class="[
                  'input w-full',
                  errors.email ? 'border-red-300 focus-visible:ring-red-500' : ''
                ]"
                placeholder="Work email"
              >
              <p v-if="errors.email" class="mt-1 text-sm text-red-600">
                {{ errors.email }}
              </p>
            </div>

            <!-- Password -->
            <div>
              <div class="relative">
                <input
                  id="password"
                  v-model="password"
                  v-bind="passwordAttrs"
                  :type="showPassword ? 'text' : 'password'"
                  autocomplete="current-password"
                  :class="[
                    'input w-full pr-10',
                    errors.password ? 'border-red-300 focus-visible:ring-red-500' : ''
                  ]"
                  placeholder="Password"
                >
                <button
                  type="button"
                  @click="togglePasswordVisibility"
                  class="absolute inset-y-0 right-0 pr-3 flex items-center"
                >
                  <Eye v-if="!showPassword" class="h-4 w-4 text-gray-400" />
                  <EyeOff v-else class="h-4 w-4 text-gray-400" />
                </button>
              </div>
              <p v-if="errors.password" class="mt-1 text-sm text-red-600">
                {{ errors.password }}
              </p>
            </div>

            <!-- Error Message -->
            <div v-if="loginError" class="p-3 bg-red-50 border border-red-200 rounded-lg">
              <p class="text-sm text-red-600">{{ loginError }}</p>
            </div>

            <!-- Login button -->
            <button
              type="button"
              @click="handleLogin"
              :disabled="authStore.isLoading"
              class="btn btn-primary w-full h-12 text-base font-semibold"
            >
              <Loader2 v-if="authStore.isLoading" class="animate-spin h-5 w-5 mr-2" />
              <span v-if="authStore.isLoading">Signing in...</span>
              <span v-else>Sign in</span>
            </button>
          </div>

     

          <!-- Footer Links -->
          <div class="flex items-center justify-center space-x-6 text-xs text-gray-500">
            <a href="#" class="hover:text-gray-700">Privacy Policy</a>
            <a href="#" class="hover:text-gray-700">Terms of Service</a>
            <a href="#" class="hover:text-gray-700">Privacy & Security</a>
          </div>
        </div>

        <!-- Demo credentials -->
        <div class="mt-8 p-4 bg-gray-50 rounded-lg">
          <p class="text-xs text-gray-600 mb-2">Demo credentials:</p>
          <p class="text-xs text-gray-500">Email: admin@example.com</p>
          <p class="text-xs text-gray-500">Password: password123</p>
        </div>
      </div>
    </div>

    <!-- Right Side - Illustration/Branding -->
    <div class="hidden lg:flex flex-1 bg-gradient-to-br from-purple-600 to-blue-600 items-center justify-center p-12">
      <div class="max-w-md text-center text-white">
        <div class="mb-8">
          <div class="w-24 h-24 mx-auto bg-white bg-opacity-20 rounded-2xl flex items-center justify-center mb-6">
            <Shield class="w-12 h-12 text-white" />
          </div>
          <h2 class="text-3xl font-bold mb-4">
            Welcome to Admin Panel
          </h2>
          <p class="text-lg text-purple-100 mb-8">
            Manage your system with powerful tools and intuitive interface. Get insights, control users, and monitor your application performance.
          </p>
        </div>

        <!-- Feature highlights -->
        <div class="space-y-4 text-left">
          <div class="flex items-center space-x-3">
            <div class="w-8 h-8 bg-white bg-opacity-20 rounded-lg flex items-center justify-center">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
              </svg>
            </div>
            <span class="text-purple-100">User Management & Role Control</span>
          </div>
          <div class="flex items-center space-x-3">
            <div class="w-8 h-8 bg-white bg-opacity-20 rounded-lg flex items-center justify-center">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
              </svg>
            </div>
            <span class="text-purple-100">Real-time Analytics & Reports</span>
          </div>
          <div class="flex items-center space-x-3">
            <div class="w-8 h-8 bg-white bg-opacity-20 rounded-lg flex items-center justify-center">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
              </svg>
            </div>
            <span class="text-purple-100">Secure & Scalable Architecture</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
